### ISSUE TITLE
'generator' was not declared in this scope 

### ISSUE THREAD

**Issue by DVB-Arduino** [daumemo/Arduino-AD9833-GPIO-only-library#1]
Hello. I compile the example for ESP32 
but I get an error "  'generator' was not declared in this scope "
 Can you fix the library?
thank you

**Comment by DVB-Arduino** [comment]
AD9833_IC generator(1, 5, 3); // creates new object with pins 1,5,3 as SCK, FSYNC, DATA
                                // and initialises IC with stopped state 
                                // (reset and sleep states are ON);

should be before Setup

**Comment by daumemo** [comment]
Thanks for noticing the mistake. I have moved generator initialisation ouside Setup.

**Comment by DVB-Arduino** [comment]
Thank you. And you need to move the usage_example.cpp to the examples folder, because the Arduino IDE compiles the example, not my sketch. I had to remove the example from the library.

**Comment by DVB-Arduino** [comment]
Also a question about the generator. After the command generator.stop(); the generator stops arbitrarily either at a high level or at a low level. Is it possible to make the level always low after stopping?

**Comment by daumemo** [comment]
Well, I have checked the IC datasheet again - don't see any straight forward way. But maybe it is possible to try doing some workarounds: for e.g. if you are using squarewave, after stop() try setting frequency to 0 and do start() stop(). Also, when using sine or triangle, the voltage should be low enough to read it as low... Sorry, it might not be much to help you with, as at the moment I don't have AD9833 dev board at hand to test it out :/
